// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsbitvdpgvjulbwhlbhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzYml0dmRwZ3ZqdWxid2hsYmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxMzIwNTksImV4cCI6MjA0ODcwODA1OX0.35NXWoGDVfE8yx_z-tjGtTPbh-fK7N6VR1axRHsAK8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);